
USE TaskManagerDb;
DROP TABLE IF EXISTS Comments;
CREATE TABLE Comments(
	CommentId CHAR(36) PRIMARY KEY,
	TaskId CHAR(36),
	CreateDate DATETIME,
	Content TEXT
);

ALTER TABLE Comments
   ADD CONSTRAINT FK_TaskId FOREIGN KEY (TaskId)
      REFERENCES Tasks (TaskId)
      ON DELETE CASCADE
      ON UPDATE CASCADE;